title: The Story of an Excpetional Student, Athlete, and Communal Member
date: 20200612
author: Swayam Singh
email: ssingh5@ebnet.org or soccerswayam@gmail.com
description: > Hello, welcome to my website, a place that will give you a 
brief description about me regarding my accomplishments, my appearance, my
social media links, and a few other things you may have not known about me.

# social links
instagram_username: swayam._.singh
snapchat_username: magicalswayam
twitter_username: swayamblogs

theme: minima
